### ISSUE TITLE
Constants on env.sh

### ISSUE THREAD

**Issue by jonasrla** [SPOClab-ca/COVFEFE#7]
I suggest the `env.sh` environment variables could be written on a `config.yml` to be consulted

**Comment by daniyall** [comment]
Thanks for the suggestion. Implemented in 00f1cfa4d849010b81ab7a0f825561b3c4c13f37 with some minor changes.

I put the config variables in a file called `config.ini` (used .ini instead of yaml becasue python has a built in parser for ini files). But now you don't need to manually source a file before running covfefe. When  run, `config.py` wil try to read variables from the environment first, then resort to the `config.ini` file.
